### ISSUE TITLE
[TODO] Review channel handling 

### ISSUE THREAD

**Issue by hron84** [dragonhall/showtime#13]
- [ ] Channels should be determined by the domain OR the channel key and they should be authorised too
- [ ] Check if all required META tag correctly set on the rendered TV page (DHTV issue?)
- [ ] Add external channel embedding based on a secred and the Referer domain name
